if: commit_message !~ /auto\/ci:\sset\sversion/
language: node_js
node_js:
  - "12.16.3"
git:
  depth: false
cache:
  directories:
    - node_modules
script:
  - git remote set-url origin https://$USER:$GITHUB_API_KEY@github.com/eigen-space/utils.git
  - yarn lint && yarn test && yarn build && npm run deploy:publish -- --branch=$TRAVIS_BRANCH;
before_install:
  - echo "registry=https://$REGISTRY/" >> .npmrc
  - echo "//$REGISTRY/:_authToken=$ACCESS_TOKEN" >> .npmrc
